// @ts-check
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

// TODO(launch): Replace with the real production domain.
// This value drives canonical URLs and the XML sitemap.
export default defineConfig({
  site: 'https://www.zzpine.com',
  integrations: [
    mdx(),
    sitemap({
      /**
       * Multilingual sitemap: pages under /{prefix}/ get xhtml:link
       * hreflang alternates; unprefixed pages are the English (default)
       * versions. Keys must match the URL prefixes generated by
       * src/pages/[lang]/[...slug].astro.
       */
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en',
          es: 'es',
          'zh-hant': 'zh-Hant',
          fr: 'fr',
          ar: 'ar',
          pt: 'pt',
          it: 'it',
          de: 'de',
          ru: 'ru',
          ja: 'ja',
          ko: 'ko',
        },
      },
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
