/**
 * Category name/heading/description translations.
 * Slugs and power ranges are language-neutral URL/data — never translated.
 *
 * The per-locale tables in src/i18n/categories/{lang}.ts are GENERATED by
 * `npm run i18n:update` from the English records in src/lib/categories.ts
 * (the single source of truth). Do not edit the generated files by hand —
 * edit the English copy and run the sync.
 */
import type { Category } from '../lib/categories';
import { DEFAULT_LOCALE, type Locale } from './config';
import { esCategories } from './categories/es';
import { zhHantCategories } from './categories/zh-hant';
import { frCategories } from './categories/fr';
import { arCategories } from './categories/ar';
import { ptCategories } from './categories/pt';
import { itCategories } from './categories/it';
import { deCategories } from './categories/de';
import { ruCategories } from './categories/ru';
import { jaCategories } from './categories/ja';
import { koCategories } from './categories/ko';

export interface CategoryContent {
  name: string;
  heading: string;
  description: string;
}

export type CategoryTranslations = Record<string, CategoryContent>;

const TABLES: Partial<Record<Locale, CategoryTranslations>> = {
  es: esCategories,
  'zh-hant': zhHantCategories,
  fr: frCategories,
  ar: arCategories,
  pt: ptCategories,
  it: itCategories,
  de: deCategories,
  ru: ruCategories,
  ja: jaCategories,
  ko: koCategories,
};

/** Minimal shape so un-translated locales fall back to the English record. */
export function localizedCategory(category: Category, locale: Locale): Category {
  if (locale === DEFAULT_LOCALE) return category;
  const t = TABLES[locale]?.[category.slug];
  if (!t) return category;
  return { ...category, name: t.name, heading: t.heading, description: t.description };
}
