/**
 * Localized route registry.
 *
 * English routes stay exactly where they are (src/pages/**). Every other
 * locale is generated by ONE dynamic route file:
 * src/pages/[lang]/[...slug].astro, which enumerates the (locale, path)
 * pairs built here and renders the matching template from src/templates/.
 *
 * The same registry drives the language switcher equivalence (a localized
 * page is always the English path behind a prefix) and can be used for
 * audits of the route matrix.
 */
import { PREFACED_LOCALES, type Locale } from './config';
import { getAllProducts, getCategoriesWithProducts } from '../lib/products';
import { getPowerCategories, powerCategoryPath } from '../lib/power-categories';

export type PageKind =
  | 'home'
  | 'products'
  | 'category'
  | 'power'
  | 'product'
  | 'about'
  | 'factory'
  | 'quality'
  | 'contact'
  | 'privacy'
  | 'blog'
  | 'blogArticle';

export interface RouteEntry {
  locale: Locale;
  /** English path — the canonical identity of the page across locales. */
  enPath: string;
  kind: PageKind;
  /** Payload needed to render: slugs / ids, resolved by the caller. */
  data: {
    category?: string;
    power?: string;
    product?: string;
    post?: string;
  };
}

/** English-language paths for every catalog-derived page. */
export function catalogEnPaths(): RouteEntry[] {
  const entries: RouteEntry[] = [{ locale: 'en', enPath: '/products/', kind: 'products', data: {} }];

  for (const category of getCategoriesWithProducts()) {
    entries.push({
      locale: 'en',
      enPath: `/products/${category.slug}/`,
      kind: 'category',
      data: { category: category.slug },
    });

    for (const power of getPowerCategories(category.slug)) {
      entries.push({
        locale: 'en',
        enPath: powerCategoryPath(category.slug, power.slug),
        kind: 'power',
        data: { category: category.slug, power: power.slug },
      });
    }
  }

  for (const product of getAllProducts()) {
    entries.push({
      locale: 'en',
      enPath: `/products/${product.category}/${product.slug}/`,
      kind: 'product',
      data: { category: product.category, product: product.slug },
    });
  }

  return entries;
}

/** Every localized (non-English) route, except blog articles (caller adds them). */
export function buildLocalizedRoutes(posts: { id: string }[] = []): {
  params: { lang: string; slug?: string };
  props: RouteEntry;
}[] {
  const english = [
    catalogEnPaths(),
    [{ locale: 'en', enPath: '/', kind: 'home', data: {} } as RouteEntry],
    [
      { locale: 'en', enPath: '/about/', kind: 'about', data: {} },
      { locale: 'en', enPath: '/factory/', kind: 'factory', data: {} },
      { locale: 'en', enPath: '/quality/', kind: 'quality', data: {} },
      { locale: 'en', enPath: '/contact/', kind: 'contact', data: {} },
      { locale: 'en', enPath: '/privacy-policy/', kind: 'privacy', data: {} },
      { locale: 'en', enPath: '/blog/', kind: 'blog', data: {} },
    ] as RouteEntry[],
    posts.map(
      (post): RouteEntry => ({
        locale: 'en',
        enPath: `/blog/${post.id}/`,
        kind: 'blogArticle',
        data: { post: post.id },
      })
    ),
  ].flat();

  const result: { params: { lang: string; slug?: string }; props: RouteEntry }[] = [];

  for (const locale of PREFACED_LOCALES) {
    for (const entry of english) {
      const enPath = entry.enPath === '/' ? '/' : entry.enPath.replace(/\/+$/, '') + '/';
      const slug = enPath === '/' ? undefined : enPath.slice(1).replace(/\/$/, '');
      result.push({
        params: { lang: locale, slug },
        props: { ...entry, locale },
      });
    }
  }

  return result;
}
