// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const arCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'عاكسات هجينة',
    heading: 'عاكسات شمسية هجينة',
    description:
      'تجمع بين التحويل الشمسي وشحن البطاريات والتفاعل مع الشبكة في جهاز واحد. مثالية لأنظمة تخزين الطاقة السكنية والتجارية.',
  },
  'grid-tie-inverters': {
    name: 'عاكسات مرتبطة بالشبكة',
    heading: 'عاكسات شمسية مرتبطة بالشبكة',
    description:
      'عاكسات سلسلة عالية الكفاءة لأنظمة الطاقة الشمسية المرتبطة بالشبكة، من الأسطح السكنية إلى محطات الطاقة الشمسية التجارية والصناعية.',
  },
  'off-grid-inverters': {
    name: 'عاكسات خارج الشبكة',
    heading: 'عاكسات طاقة خارج الشبكة',
    description:
      'عاكسات بموجة جيبية نقية لأنظمة تعمل بالبطاريات خارج الشبكة — مثالية للمناطق النائية، والمواقع غير المتصلة بالشبكة، والمناطق ذات الانقطاعات المتكررة. تحويل من التيار المستمر إلى المتردد بدون شاحن شمسي مدمج؛ يمكن ربطها بشاحن أو منظم شمسي خارجي.',
  },
  accessories: {
    name: 'ملحقات العاكسات',
    heading: 'ملحقات العاكسات',
    description:
      'وحدات Wi-Fi ووحدات اتصال وكابلات وأطقم تركيب تكمل تركيب العاكس الخاص بك.',
  },
};
