// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const deCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'Hybrid-Wechselrichter',
    heading: 'Hybride Solar-Wechselrichter',
    description:
      'Verbinden Solarwandlung, Batterieladung und Netzinteraktion in einem Gerät. Ideal für private und gewerbliche Energiespeichersysteme.',
  },
  'grid-tie-inverters': {
    name: 'Netzgekoppelte Wechselrichter',
    heading: 'Solar-Wechselrichter für das Netz',
    description:
      'Hocheffiziente String-Wechselrichter für netzgekoppelte PV-Anlagen, von Wohngebäudedächern bis zu gewerblichen und industriellen Solarparks.',
  },
  'off-grid-inverters': {
    name: 'Off-Grid-Wechselrichter',
    heading: 'Off-Grid-Stromwechselrichter',
    description:
      'Reine Sinuswellen-Wechselrichter für batteriegestützte autarke Systeme — ideal für abgelegene Gebiete, Standorte ohne Netzzugang und Regionen mit häufigen Stromausfällen. DC/AC-Umwandlung ohne integrierten Solarladeregler; kombinierbar mit externem Ladegerät oder Solarregler.',
  },
  accessories: {
    name: 'Wechselrichter-Zubehör',
    heading: 'Wechselrichter-Zubehör',
    description:
      'WLAN-Sticks, Kommunikationsmodule, Kabel und Montagekits, die Ihre Wechselrichter-Installation vervollständigen.',
  },
};
