// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const esCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'Inversores híbridos',
    heading: 'Inversores solares híbridos',
    description:
      'Combinan conversión solar, carga de baterías e interacción con la red en un solo equipo. Ideales para sistemas residenciales y comerciales de almacenamiento de energía.',
  },
  'grid-tie-inverters': {
    name: 'Inversores con conexión a red',
    heading: 'Inversores solares para red',
    description:
      'Inversores de string de alta eficiencia para sistemas fotovoltaicos conectados a red, desde tejados residenciales hasta plantas solares comerciales e industriales.',
  },
  'off-grid-inverters': {
    name: 'Inversores aislados (off-grid)',
    heading: 'Inversores de potencia aislados',
    description:
      'Inversores de onda senoidal pura para sistemas autónomos: estaciones base de telecomunicaciones, electrificación rural y energía de respaldo.',
  },
  accessories: {
    name: 'Accesorios para inversores',
    heading: 'Accesorios para inversores',
    description:
      'Módulos Wi-Fi, módulos de comunicación, cables y kits de montaje que completan la instalación de su inversor.',
  },
};
