// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const frCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'Onduleurs hybrides',
    heading: 'Onduleurs solaires hybrides',
    description:
      "Combinent conversion solaire, charge de batterie et interaction avec le réseau en un seul appareil. Idéaux pour le stockage d'énergie résidentiel et commercial.",
  },
  'grid-tie-inverters': {
    name: 'Onduleurs raccordés au réseau',
    heading: 'Onduleurs solaires pour réseau',
    description:
      'Onduleurs de string à haute efficacité pour systèmes PV raccordés au réseau, des toitures résidentielles aux centrales solaires commerciales et industrielles.',
  },
  'off-grid-inverters': {
    name: 'Onduleurs hors réseau',
    heading: 'Onduleurs de puissance hors réseau',
    description:
      'Onduleurs à onde sinusoïdale pure pour systèmes autonomes sur batteries — idéals pour les zones reculées, les sites sans raccordement au réseau et les régions à coupures fréquentes. Conversion CC en CA sans chargeur solaire intégré ; à associer à un chargeur ou un régulateur solaire externe.',
  },
  accessories: {
    name: 'Accessoires pour onduleurs',
    heading: 'Accessoires pour onduleurs',
    description:
      "Clés Wi-Fi, modules de communication, câbles et kits de montage qui complètent l'installation de votre onduleur.",
  },
};
