// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const itCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'Inverter ibridi',
    heading: 'Inverter solari ibridi',
    description:
      "Combinano conversione solare, ricarica delle batterie e interazione con la rete in un'unica unità. Ideali per sistemi di accumulo residenziali e commerciali.",
  },
  'grid-tie-inverters': {
    name: 'Inverter connessi alla rete',
    heading: 'Inverter solari per rete',
    description:
      'Inverter string ad alta efficienza per impianti fotovoltaici collegati alla rete, dai tetti residenziali agli impianti solari commerciali e industriali.',
  },
  'off-grid-inverters': {
    name: 'Inverter off-grid',
    heading: 'Inverter di potenza off-grid',
    description:
      'Inverter a onda sinusoidale pura per sistemi autonomi — stazioni radio base, elettrificazione rurale e alimentazione di riserva.',
  },
  accessories: {
    name: 'Accessori per inverter',
    heading: 'Accessori per inverter',
    description:
      "Chiavette Wi-Fi, moduli di comunicazione, cavi e kit di montaggio che completano l'installazione del vostro inverter.",
  },
};
