// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const jaCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'ハイブリッドインバーター',
    heading: 'ハイブリッド太陽光インバーター',
    description:
      '太陽光変換・バッテリー充電・系統連係を1台に統合。住宅用・業務用蓄電システムに最適です。',
  },
  'grid-tie-inverters': {
    name: '系統連系インバーター',
    heading: '系統連系太陽光インバーター',
    description:
      '住宅屋根から商業・産業用太陽光発電所まで、系統連系太陽光発電システム向けの高効率ストリングインバーター。',
  },
  'off-grid-inverters': {
    name: 'オフグリッドインバーター',
    heading: 'オフグリッド電源インバーター',
    description:
      '独立電源システム向けの正弦波インバーター——通信基地局、農村電化、非常用電源に。',
  },
  accessories: {
    name: 'インバーターアクセサリー',
    heading: 'インバーターアクセサリー',
    description:
      'Wi-Fiモジュール、通信モジュール、ケーブル、取付キットなど、インバーター設備を完成させる付属品。',
  },
};
