// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const koCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: '하이브리드 인버터',
    heading: '하이브리드 태양광 인버터',
    description:
      '태양광 변환, 배터리 충전, 계통 연계를 한 대에 통합했습니다. 주거용 및 상업용 에너지 저장 시스템에 이상적입니다.',
  },
  'grid-tie-inverters': {
    name: '계통 연계 인버터',
    heading: '계통 연계 태양광 인버터',
    description:
      '주거용 옥상부터 상업·산업용 태양광 발전소까지, 계통 연계 태양광 발전 시스템을 위한 고효율 스트링 인버터입니다.',
  },
  'off-grid-inverters': {
    name: '오프그리드 인버터',
    heading: '오프그리드 전원 인버터',
    description:
      '독립 전원 시스템을 위한 순수 정현파 인버터 — 통신 기지국, 농촌 전기화, 비상 전원에 적합합니다.',
  },
  accessories: {
    name: '인버터 액세서리',
    heading: '인버터 액세서리',
    description:
      'Wi-Fi 모듈, 통신 모듈, 케이블, 설치 키트 등 인버터 설치를 완성하는 액세서리입니다.',
  },
};
