// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const ruCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: 'Гибридные инверторы',
    heading: 'Гибридные солнечные инверторы',
    description:
      'Объединяют солнечное преобразование, зарядку аккумуляторов и взаимодействие с сетью в одном устройстве. Идеальны для бытовых и коммерческих систем накопления энергии.',
  },
  'grid-tie-inverters': {
    name: 'Сетевые инверторы',
    heading: 'Сетевые солнечные инверторы',
    description:
      'Высокоэффективные строковые инверторы для сетевых фотоэлектрических систем — от жилых крыш до коммерческих и промышленных солнечных электростанций.',
  },
  'off-grid-inverters': {
    name: 'Автономные инверторы',
    heading: 'Автономные силовые инверторы',
    description:
      'Инверторы с чистой синусоидой для автономных систем электроснабжения — базовые станции связи, электрификация сельских районов и резервное питание.',
  },
  accessories: {
    name: 'Аксессуары для инверторов',
    heading: 'Аксессуары для инверторов',
    description:
      'Wi-Fi-модули, модули связи, кабели и монтажные комплекты, дополняющие установку инвертора.',
  },
};
