// GENERATED FILE — do not edit by hand.
// Regenerated by `npm run i18n:update` from the English single source of
// truth. Hand edits to a field are overwritten when the English version of
// that field changes; fields that are absent fall back to English at build
// time (see src/i18n/product-content.ts / blog-content.ts / category-content.ts).

import type { CategoryTranslations } from '../category-content';

export const zhHantCategories: CategoryTranslations = {
  'hybrid-inverters': {
    name: '混合型逆變器',
    heading: '混合型太陽能逆變器',
    description:
      '結合太陽能轉換、電池充電與電網互動於一體。適用於住宅與商業儲能系統。',
  },
  'grid-tie-inverters': {
    name: '併網型逆變器',
    heading: '併網型太陽能逆變器',
    description:
      '適用於併網型太陽能光電系統的高效率組串型逆變器，涵蓋住宅屋頂到工商業太陽能電站。',
  },
  'off-grid-inverters': {
    name: '離網型逆變器',
    heading: '離網型電力逆變器',
    description:
      '適用於獨立電力系統的純正弦波逆變器——電信基地台、偏鄉供電與備用電源。',
  },
  accessories: {
    name: '逆變器配件',
    heading: '逆變器配件',
    description:
      'Wi-Fi 模組、通訊模組、線材與安裝支架組，完善您的逆變器安裝。',
  },
};
